---
title: "T7 warmx soil temperature Plots"
author: "Adrian Noecker"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

COLLABORATORS: Kara Dobson, Phoebe Zarnetske, Mark Hammond, Moriah Young
DATA INPUT:  csv from the shared Google drive  
DATA OUTPUT: Code and Rmd are in the scripts folder in Github  
PROJECT: REX
```{r}

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Clear all existing data
rm(list=ls())

# Load packages
library(tidyverse)
library(ggpubr)
library(RColorBrewer)
library(plotrix)

# Set working directory from .Renviron
# dir <- Sys.getenv("DATA_DIR")
# list.files(dir)
setwd("G:/Shared drives/KBS_LTER_REX/data/sensors/OTC Footprints/L1")

# Read in data
soiltemp <- read.csv("T7_warmx_soil_sensors_L1.csv")

# re-making the data column a date
soiltemp$Date_Time <- as.POSIXct(soiltemp$sample_datetime, format = "%Y-%m-%d %H:%M:%S")
str(soiltemp)

# Specifying the order that we want the treatments to be listed in the figures on the x-axis
level_order <- c('irrigated_control', 'ambient', 'drought', 'warmed','warmed_drought')

```

```{r}
# create new dataframe with only data from april - august from 7 AM - 7 PM (growing season during the day)
# this is mainly what we'll work with for figures (could always adjust the parameters as needed)
soil_season <- soiltemp
soil_season$month <- format(soil_season$Date_Time,format="%m")
soil_season$year <- format(soil_season$Date_Time,format="%Y")
soil_season$hour <- format(soil_season$Date_Time, format="%H")
soil_season$day <- format(soil_season$Date_Time, format="%d")
soil_season <- soil_season %>%
  filter(hour > "06") %>%
  filter(hour < "20")
soil_season_sum <- soil_season %>%
  filter(hour > "06") %>%
  filter(hour < "20") %>%
  filter(month > "05") %>%
  filter(month < "09")
```

```{r}
# taking 2022 soil average for January -  December (sampling period)
soil_season_sum$date <- paste0(soil_season_sum$month,"",soil_season$day)
soil_season_sum$date <- as.numeric(soil_season_sum$date)

# take average per day, per rep, per treatment
soil_sam <- soil_season %>%
  group_by(date, Subplot_Descriptions) %>%
  summarize(average_temp = mean(temperature, na.rm = TRUE))
           se_temp = std.error(average_temp, na.rm = TRUE)

# averaging over each rep, n varies between treatments
soil_sam <- soil_sam %>%
  group_by(Subplot_Descriptions) %>%
  summarize(avg_temp = mean(average_temp, na.rm = TRUE),
            se_temp = std.error(average_temp, na.rm = TRUE))
```