---
title: "REX: T7 warmx Phenology Flowering Analyses"
author: "Moriah Young"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

COLLABORATORS: Kara Dobson, Phoebe Zarnetske, Mark Hammond
DATA INPUT:  L1 csv cleaned data from the shared Google drive  
DATA OUTPUT: Code and Rmd are in the scripts folder in Github L2 folder
PROJECT: REX  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Clear all existing data
rm(list=ls())

# Load packages
library(bbmle)
library(lmerTest)
library(fitdistrplus)
library(sjPlot)
library(car)
library(emmeans)
library(tidyverse)
library(ggpubr)
library(jtools) #summ 
library(rstatix)
library(RColorBrewer)
library(plotrix)
library(stats)

# Set working directory from .Renviron
dir <- Sys.getenv("DATA_DIR")
list.files(dir)

# Read in data
phen <- read.csv(file.path(dir, "T7_plant_phenology/L1/T7_warmx_plant_phenology_L1.csv"))

# remove climate treatment plots we aren't interested in here (i.e., insecticide plots)
phen <- phen %>%
  filter(!(Subplot_Descriptions=='drought_insecticide' |
             Subplot_Descriptions=='insecticide' |
             Subplot_Descriptions=='warmed_drought_insecticide' |
             Subplot_Descriptions=='warmed_insecticide'))

# make a column for Year
phen$Date <- as.Date(phen$Date)
phen$Year <- format(phen$Date, "%Y")

# selecting just "Flower" action 
flwr <- subset(phen, Action == "Flower")
flwr$Date <- as.Date(flwr$Date)

# Select by date of first flower
first_flwr <- flwr %>%
  group_by(Unique_ID, Subplot_Descriptions, Replicate, Footprint_Location, Code, Action, Year) %>%
  summarize(min_julian = min(Julian, na.rm=T))

# create a separate dataframe for select species of interest
soca <- subset(first_flwr, Code == "Soca") # goldenrod
trpr <- subset(first_flwr, Code == "Trpr") # red clover
trpr22 <- subset(first_flwr, Year == "2022") # just 2022 data
```

Data Exploration for all species
```{r}
# checking raw data
hist(first_flwr$min_julian)
qqnorm(first_flwr$min_julian)
shapiro.test(first_flwr$min_julian) # pvalue is < 0.05 so we cannot reject the null hypothesis that the data is normal (aka not normally distributed)

# Exploring distributions for these data:
descdist(first_flwr$min_julian, discrete = FALSE)

m1 <- lmer(log(min_julian) ~ Subplot_Descriptions + (1|Replicate/Footprint_Location), data = first_flwr, REML=F)
hist(resid(m1))
qqnorm(resid(m1))
plot(m1)
```

Data Exploration for Soca
```{r}
# checking raw data
hist(soca$min_julian)
qqnorm(soca$min_julian)
shapiro.test(soca$min_julian) # pvalue is < 0.05 so we cannot reject the null hypothesis that the data is normal (aka not normally distributed) but it is close (p-value = 0.04623)

# Exploring distributions for these data:
descdist(soca$min_julian, discrete = FALSE) # normal

m1s <- lmer(min_julian ~ Subplot_Descriptions + (1|Replicate/Footprint_Location), data = soca, REML=F)
hist(resid(m1s))
qqnorm(resid(m1s))
plot(m1s)

# homogeneity of variance? yes, p >0.05 (no significant difference between the group variances)
leveneTest(residuals(m1s) ~ soca$Subplot_Descriptions)
```

Model Exploration
```{r}
summary(m1s)
emmeans(m1s, list(pairwise ~ Subplot_Descriptions), adjust = "tukey")
```

Data Exploration for Trpr 2021 & 2022
```{r}
# checking raw data
hist(trpr$min_julian)
qqnorm(trpr$min_julian)
shapiro.test(trpr$min_julian) # pvalue is < 0.05 so we cannot reject the null hypothesis that the data is normal (aka not normally distributed) but it is close (p-value = 0.04623)

# Exploring distributions for these data:
descdist(trpr$min_julian, discrete = FALSE) # normal

m1t <- lmer(min_julian ~ Subplot_Descriptions + (1|Replicate/Footprint_Location), data = trpr, REML=F)
hist(resid(m1t))
qqnorm(resid(m1t))
plot(m1t)
outlierTest(m1t) # row 9

trpr_nooutlier <- trpr[-9,] # remove outlier

# checking raw data without outlier
hist(trpr_nooutlier$min_julian)
qqnorm(trpr_nooutlier$min_julian)
shapiro.test(trpr_nooutlier$min_julian) # pvalue is < 0.05 so we cannot reject the null hypothesis that the data is normal (aka not normally distributed) 

# Exploring distributions for these data:
descdist(trpr_nooutlier$min_julian, discrete = FALSE)

m1t <- lmer(log(min_julian) ~ Subplot_Descriptions + (1|Replicate/Footprint_Location), data = trpr_nooutlier, REML=F)
hist(resid(m1t))
qqnorm(resid(m1t))
plot(m1t)
outlierTest(m1t) # row 43

# homogeneity of variance? yes, p >0.05 (no significant difference between the group variances)
leveneTest(residuals(m1t) ~ trpr_nooutlier$Subplot_Descriptions)
```
Model Exploration
```{r}
m2t <- lmer(log(min_julian) ~ Subplot_Descriptions + Year + (1|Replicate/Footprint_Location), data = trpr_nooutlier, REML=F)
summary(m1t)
summary(m2t)
emmeans(m1t, list(pairwise ~ Subplot_Descriptions), adjust = "tukey")
emmeans(m2t, list(pairwise ~ Subplot_Descriptions + Year), adjust = "tukey")
```

Just trpr 2022 data
```{r}
# checking raw data
hist(trpr22$min_julian)
qqnorm(trpr22$min_julian)
shapiro.test(trpr22$min_julian) # pvalue is < 0.05 so we cannot reject the null hypothesis that the data is normal (aka not normally distributed) but it is close (p-value = 0.04623)

# Exploring distributions for these data:
descdist(trpr22$min_julian, discrete = FALSE) 

m1t <- lmer(min_julian ~ Subplot_Descriptions + (1|Replicate/Footprint_Location), data = trpr22, REML=F)
hist(resid(m1t))
qqnorm(resid(m1t))
plot(m1t)
outlierTest(m1t) # row 189

trpr_nooutlier <- trpr[-9,] # remove outlier

# checking raw data without outlier
hist(trpr_nooutlier$min_julian)
qqnorm(trpr_nooutlier$min_julian)
shapiro.test(trpr_nooutlier$min_julian) # pvalue is < 0.05 so we cannot reject the null hypothesis that the data is normal (aka not normally distributed) 

# Exploring distributions for these data:
descdist(trpr_nooutlier$min_julian, discrete = FALSE)

m1t <- lmer(log(min_julian) ~ Subplot_Descriptions + (1|Replicate/Footprint_Location), data = trpr22, REML=F)
hist(resid(m1t))
qqnorm(resid(m1t))
plot(m1t)
outlierTest(m1t) # row 43

# homogeneity of variance? yes, p >0.05 (no significant difference between the group variances)
leveneTest(residuals(m1t) ~ trpr22$Subplot_Descriptions)
```

Model Exploration
```{r}
# re-leveling the dataframe & re-running model for post-hoc comparisions
trpr22 <- within(trpr22, Subplot_Descriptions <- relevel(factor(Subplot_Descriptions), ref = "drought"))
trpr22 <- within(trpr22, Subplot_Descriptions <- relevel(factor(Subplot_Descriptions), ref = "irrigated_control"))
trpr22 <- within(trpr22, Subplot_Descriptions <- relevel(factor(Subplot_Descriptions), ref = "warmed"))
trpr22 <- within(trpr22, Subplot_Descriptions <- relevel(factor(Subplot_Descriptions), ref = "warmed_drought"))
trpr22 <- within(trpr22, Subplot_Descriptions <- relevel(factor(Subplot_Descriptions), ref = "ambient"))

summary(m1t)
emmeans(m1t, list(pairwise ~ Subplot_Descriptions), adjust = "tukey")
```
