---
title: "REX: T7 warmx Phenology Green-up Analyses"
author: "Moriah Young"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

COLLABORATORS: Kara Dobson, Phoebe Zarnetske, Mark Hammond
DATA INPUT:  L1 csv cleaned data from the shared Google drive  
DATA OUTPUT: Code and Rmd are in the scripts folder in Github L2 folder
PROJECT: REX  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Clear all existing data
rm(list=ls())

# Load packages
library(bbmle)
library(lmerTest)
library(fitdistrplus)
library(sjPlot)
library(car)
library(emmeans)
library(tidyverse)
library(ggpubr)
library(jtools) #summ 
library(rstatix)
library(RColorBrewer)
library(plotrix)
library(stats)

# Set working directory from .Renviron
dir <- Sys.getenv("DATA_DIR")
list.files(dir)

# Read in data
plantcomp <- read.csv(file.path(dir, "T7_plant_comp/L1/T7_warmx_plantcomp_L1.csv"))

# make a column for Year
plantcomp$Date <- as.Date(plantcomp$Date)
plantcomp$Year <- format(plantcomp$Date, "%Y")

# removing treatments we aren't interested in
plantcomp_noinsect <- plantcomp %>%
  filter(!(Subplot_Descriptions=='drought_insecticide' |
                   Subplot_Descriptions=='insecticide' |
                   Subplot_Descriptions=='warmed_drought_insecticide' |
                   Subplot_Descriptions=='irrigated_control' |
                   Subplot_Descriptions=='warmed_insecticide'))

# remove species we aren't interested in (i.e., unknowns and unsorted plant material)
plantcomp_noinsect <- plantcomp_noinsect %>%
  filter(!(Code=='Living Vegetation' |
             Code=='Non-Living Vegetation' |
             Code=='Moss' |
             Code=='Soil' |
             Code == 'total_living' |
             Code == 'total_non_living' |
             Code == 'soil_char' |
             Code == 'standing_dead' |
             Code =='Litter')) 

plantcomp_noinsect21 <- subset(plantcomp_noinsect, Year == "2021")
plantcomp_noinsect22 <- subset(plantcomp_noinsect, Year == "2022")

# removing rep 2, footprint 2, subplot a because OTC blew over 3/31/2022 and wasn't fixed until 4/25/2022
# "T7_R2_OC_W_2a" = UniqueID
plantcomp_noinsect22 <- plantcomp_noinsect22 %>%
  filter(!(Unique_ID =='T7_R2_OC_W_2a'))

# remove dates before prescribed burn took place
# 2022 = 3/29/2022 = Julian date 
# 2021 = ~3/17/2021
plantcomp_noinsect21 <- plantcomp_noinsect21 %>%
  filter(!(Julian < 89))
plantcomp_noinsect22 <- plantcomp_noinsect22 %>%
  filter(!(Julian < 104))

plantcomp_noinsect <- full_join(plantcomp_noinsect21, plantcomp_noinsect22)

# Select by date of first record of plant comp
greenup_noinsect <- plantcomp_noinsect %>%
  group_by(Unique_ID, Subplot_Descriptions, Code, Replicate, Footprint_Location, Year) %>%
  summarize(min_julian = min(Julian, na.rm=T))

# create a separate dataframe for select species of interest
soca <- subset(greenup_noinsect, Code == "Soca") # goldenrod
soca21 <- subset(soca, Year == "2021") # just 2021 data
soca22 <- subset(soca, Year == "2022") # just 2022 data
trpr <- subset(greenup_noinsect, Code == "Trpr") # red clover
trpr21 <- subset(trpr, Year == "2021") # just 2021 data
trpr22 <- subset(trpr, Year == "2022") # just 2022 data
```

Data Exploration for green-up all species and both years
```{r}
# checking raw data
hist(greenup_noinsect$min_julian)
qqnorm(greenup_noinsect$min_julian)
shapiro.test(greenup_noinsect$min_julian) # pvalue is < 0.05 so we cannot reject the null hypothesis that the data is normal (aka not normally distributed)

# Exploring distributions for these data:
descdist(greenup_noinsect$min_julian, discrete = FALSE)

m1 <- lmer(log(min_julian) ~ Subplot_Descriptions + (1|Replicate/Footprint_Location), data = greenup_noinsect, REML=F)
hist(resid(m1))
qqnorm(resid(m1))
plot(m1)
```

Model Exploration
```{r}
m2 <- lmer(log(min_julian) ~ Subplot_Descriptions + as.factor(Year) + (1|Replicate/Footprint_Location), data = greenup_noinsect, REML=F)
summary(m1)
emmeans(m1, list(pairwise ~ Subplot_Descriptions), adjust = "tukey")

summary(m2)
emmeans(m2, list(pairwise ~ Subplot_Descriptions), adjust = "tukey")
emmeans(m2, list(pairwise ~ Subplot_Descriptions + as.factor(Year)), adjust = "tukey")
```

Data Exploration for Trpr
```{r}
# checking raw data
hist(trpr$min_julian)
qqnorm(trpr$min_julian)
shapiro.test(trpr$min_julian) # pvalue is < 0.05 so we cannot reject the null hypothesis that the data is normal (aka not normally distributed)

# Exploring distributions for these data:
descdist(trpr$min_julian, discrete = FALSE)

m1t <- lmer(log(min_julian) ~ Subplot_Descriptions + (1|Replicate/Footprint_Location), data = trpr, REML=F)
hist(resid(m1t))
qqnorm(resid(m1t))
plot(m1t)
```

Model Exploration
```{r}
m2t <- lmer(log(min_julian) ~ Subplot_Descriptions + as.factor(Year) + (1|Replicate/Footprint_Location), data = greenup_noinsect, REML=F)
summary(m1t)
emmeans(m1t, list(pairwise ~ Subplot_Descriptions), adjust = "tukey")

summary(m2t)
emmeans(m2t, list(pairwise ~ Subplot_Descriptions), adjust = "tukey")
emmeans(m2t, list(pairwise ~ Subplot_Descriptions + as.factor(Year)), adjust = "tukey")
```
