---
title: "REX: T7 warmx Phenology Flowering Plots"
author: "Moriah Young"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

COLLABORATORS: Kara Dobson, Phoebe Zarnetske, Mark Hammond
DATA INPUT:  L1 csv cleaned data from the shared Google drive  
DATA OUTPUT: Code and Rmd are in the scripts folder in Github  
PROJECT: REX  

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Clear all existing data
rm(list=ls())

# Load packages
library(bbmle)
library(lmerTest)
library(fitdistrplus)
library(sjPlot)
library(car)
library(emmeans)
library(tidyverse)
library(ggpubr)
library(jtools) #summ 
library(rstatix)
library(RColorBrewer)
library(plotrix)

# Set working directory from .Renviron
dir <- Sys.getenv("DATA_DIR")
list.files(dir)

# Read in data
phen <- read.csv(file.path(dir, "T7_plant_phenology/L1/T7_warmx_plant_phenology_L1.csv"))

# selecting just "Flower" action 
flwr <- subset(phen, Action == "Flower")
flwr$Date <- as.Date(flwr$Date)

# make a column for Year
flwr$Year <- format(flwr$Date, "%Y")

flwr_21 <- subset(flwr, Year == "2021")
flwr_22 <- subset(flwr, Year == "2022")

# Specifying the order that we want the treatments to be listed in the figures on the x-axis
level_order <- c('ambient', 'drought','warmed','warmed_drought')
```

All years
```{r}
# need to subset by Julian date bc 2022 is not finished yet - last julian date of data collected for 2022 at this time is 210
flwr_21_subset <- subset(flwr_21, Julian <= "208")
flwr_22_subset <- subset(flwr_22, Julian <= "208")
flwr_subset <- full_join(flwr_21_subset, flwr_22_subset)
flwr_subset <- subset(flwr_subset, Subplot_Descriptions != "irrigated_control")

# Select by date of first flower
first_flwr_subset <- flwr_subset %>%
  group_by(Unique_ID, Subplot_Descriptions, Code, Action, Year) %>%
  summarize(min_julian = min(Julian, na.rm=T))

# Average first Flower Date by plot
avg_first_flwr_subset <- first_flwr_subset%>%
  group_by(Subplot_Descriptions, Action, Year) %>%
  summarize(avg_min_julian = mean(min_julian, na.rm=T),
            se = std.error(min_julian, na.rm = TRUE))

first_flwr_subset <- first_flwr_subset %>% 
        filter(!(Subplot_Descriptions=='drought_insecticide' |
                         Subplot_Descriptions=='insecticide' |
                         Subplot_Descriptions=='warmed_drought_insecticide' |
                         Subplot_Descriptions=='warmed_insecticide'|
                         Subplot_Descriptions == "irrigated_control"))

avg_first_flwr_subset <- avg_first_flwr_subset %>% 
        filter(!(Subplot_Descriptions=='drought_insecticide' |
                         Subplot_Descriptions=='insecticide' |
                         Subplot_Descriptions=='warmed_drought_insecticide' |
                         Subplot_Descriptions=='warmed_insecticide'|
                         Subplot_Descriptions == "irrigated_control"))

ggplot(avg_first_flwr_subset, aes(x = Subplot_Descriptions, y = avg_min_julian, fill = as.factor(Year))) +
        geom_bar(position = "dodge", stat = "identity", col = "black") +
        geom_errorbar(aes(ymin = avg_min_julian - se, ymax = avg_min_julian + se), width = 0.2,
                      position = position_dodge(0.9)) +
        labs(x = "Treatment", y = bquote("Julian Date of First Flower"), fill="Year") +
        scale_x_discrete(limits = level_order,
                         labels=c("ambient" = "Ambient",
                                  "warmed" = "Warmed",
                                  "drought" = "Drought",
                                  "warmed_drought" = "Warmed +\n Drought")) +
        #scale_fill_manual(labels=c("2021","2022")) +
        theme(legend.position = "top")

png("firstflwr_noninsect_both_years_boxplot_L2.png", units="in", width=6, height=6, res=300)
ggplot(first_flwr_subset, aes(x = Subplot_Descriptions, y = min_julian, fill = Year)) +
        geom_boxplot(color = "black", outlier.shape = NA) +
        labs(x = "Treatment", y = "Average Julian Date of First Flower", fill = "Year") +
        geom_jitter(shape=16, position=position_jitter(0.2)) +
        scale_fill_manual(values=c("deepskyblue", "darkslategray"), # specify colors here
                    labels=c("2021","2022")) + # specify species names here
        theme(legend.text = element_text(size=16),
              legend.title = element_text(size=16)) +
        scale_x_discrete(labels=c("ambient" = "Ambient",
                                  "warmed" = "Warmed",
                                  "drought"="Drought",
                                  "warmed_drought"="Warmed +\n Drought")) +
        theme(legend.position="top")
dev.off
```

2021
```{r}
# Select by date of first flower
first_flwr_21 <- flwr_21 %>%
  group_by(Unique_ID, Subplot_Descriptions, Code, Action) %>%
  summarize(min_julian = min(Julian, na.rm=T))

# Average first Flower Date by plot
avg_first_flwr_21 <- first_flwr_21 %>%
  group_by(Subplot_Descriptions, Action) %>%
  summarize(avg_min_julian = mean(min_julian, na.rm=T),
            se = std.error(min_julian, na.rm = TRUE))

# create a separate dataframe for select species of interest
# first flower
soca_21 <- subset(first_flwr_21, Code == "Soca") # goldenrod
# Average first Flower Date by plot
avg_first_soca_21 <- soca_21 %>%
  group_by(Subplot_Descriptions, Action) %>%
  summarize(avg_min_julian = mean(min_julian, na.rm=T),
            se = std.error(min_julian, na.rm = TRUE))

# first flower
trpr_21 <- subset(first_flwr_21, Code == "Trpr") # red clover
# Average first Flower Date by plot
avg_first_trpr_21 <- trpr_21 %>%
  group_by(Subplot_Descriptions, Action) %>%
  summarize(avg_min_julian = mean(min_julian, na.rm=T),
            se = std.error(min_julian, na.rm = TRUE))
```

2022
```{r}
# Select by date of first flower
first_flwr_22 <- flwr_22 %>%
  group_by(Unique_ID, Subplot_Descriptions, Code, Action) %>%
  summarize(min_julian = min(Julian, na.rm=T))

# Average first Flower Date by plot
avg_first_flwr_22 <- first_flwr_22 %>%
  group_by(Subplot_Descriptions, Action) %>%
  summarize(avg_min_julian = mean(min_julian, na.rm=T),
            se = std.error(min_julian, na.rm = TRUE))

# first flower
trpr_22 <- subset(first_flwr_22, Code == "Trpr") # red clover
# Average first Flower Date by plot
avg_first_trpr_22 <- trpr_22 %>%
  group_by(Subplot_Descriptions, Action) %>%
  summarize(avg_min_julian = mean(min_julian, na.rm=T),
            se = std.error(min_julian, na.rm = TRUE))
```

2021 Soca plots
```{r}
soca_21_noinsect <- soca_21 %>%
  filter(!(Subplot_Descriptions=='drought_insecticide' |
             Subplot_Descriptions=='insecticide' |
             Subplot_Descriptions=='warmed_drought_insecticide' |
             Subplot_Descriptions=='warmed_insecticide' |
                   Subplot_Descriptions == "irrigated_control"))

avg_first_soca_21_noinsect <- avg_first_soca_21 %>% 
        filter(!(Subplot_Descriptions=='drought_insecticide' |
             Subplot_Descriptions=='insecticide' |
             Subplot_Descriptions=='warmed_drought_insecticide' |
             Subplot_Descriptions=='warmed_insecticide'|
                   Subplot_Descriptions == "irrigated_control"))

# Box plot
png("soca_noninsect_firstflwr_2021_boxplot_L2.png", units="in", width=6, height=6, res=300)
ggplot(soca_21_noinsect, aes(x = Subplot_Descriptions, y = min_julian, fill = Subplot_Descriptions)) +
        geom_boxplot(color = "black", outlier.shape = NA) +
        labs(x = "Treatment", y = "2021 S. canadensis\n Average Julian Date of First Flower", fill = "Subplot_Descriptions") +
        geom_jitter(shape=16, position=position_jitter(0.2)) +
        scale_fill_manual(values = c("ambient" = "darkblue", "drought" = "gray58", "irrigated_control" =
                                             "deepskyblue", "warmed" = "red2", "warmed_drought" = "darkred")) +
        theme(legend.text = element_text(size=16),
              legend.title = element_text(size=16)) +
        scale_x_discrete(labels=c("ambient" = "Ambient",
                                  "warmed" = "Warmed",
                                  "drought"="Drought",
                                  "warmed_drought"="Warmed +\n Drought")) +
        theme(legend.position="none")
dev.off

# Bar plot 
ggplot(avg_first_soca_21_noinsect, aes(x = Subplot_Descriptions, y = avg_min_julian, fill = Subplot_Descriptions)) +
  geom_jitter(shape=16, position=position_jitterdodge(), alpha = 0.6, aes(colour = Subplot_Descriptions)) +
  geom_bar(stat = "identity") +
  geom_errorbar(aes(ymin = avg_min_julian - se, ymax = avg_min_julian + se), width = 0.2,
                position = "identity") +
  scale_fill_manual(values = c("ambient" = "darkblue", "drought" = "gray58", "irrigated_control" =
                                             "deepskyblue", "warmed" = "red2", "warmed_drought" = "darkred")) +
  labs(x = "Treatment", y = "Average Julian Date of First Flower") +
  scale_x_discrete(labels=c("ambient" = "Ambient",
                                  "warmed" = "Warmed",
                                  "drought"="Drought",
                                  "warmed_drought"="Warmed +\n Drought")) +
  theme_classic() +
  theme(legend.position = "none")
```

Trpr plots both years
```{r}
trpr_21$Year <- 2021
trpr_22$Year <- 2022
trpr <- full_join(trpr_21, trpr_22)

# Average first Flower Date by plot
avg_first_flwr_trpr <- trpr %>%
  group_by(Subplot_Descriptions, Action, Year) %>%
  summarize(avg_min_julian = mean(min_julian, na.rm=T),
            se = std.error(min_julian, na.rm = TRUE))

avg_first_flwr_trpr_noinsect <- avg_first_flwr_trpr %>% 
        filter(!(Subplot_Descriptions=='drought_insecticide' |
             Subplot_Descriptions=='insecticide' |
             Subplot_Descriptions=='warmed_drought_insecticide' |
             Subplot_Descriptions=='warmed_insecticide'|
                   Subplot_Descriptions == "irrigated_control"))

ggplot(avg_first_flwr_trpr_noinsect, aes(x = Subplot_Descriptions, y = avg_min_julian, fill = as.factor(Year))) +
        geom_bar(position = "dodge", stat = "identity", col = "black") +
        geom_errorbar(aes(ymin = avg_min_julian - se, ymax = avg_min_julian + se), width = 0.2,
                      position = position_dodge(0.9)) +
        labs(x = "Treatment", y = "T. pratense Julian Date of First Flower", fill="Year") +
        scale_x_discrete(limits = level_order,
                         labels=c("ambient" = "Ambient",
                                  "warmed" = "Warmed",
                                  "drought" = "Drought",
                                  "warmed_drought" = "Warmed +\n Drought")) +
        #scale_fill_manual(labels=c("2021","2022")) +
        theme(legend.position = "top")

trpr_noinsect <- trpr_noinsect %>% 
        filter(!(Subplot_Descriptions=='irrigated_control'))

png("trpr_noninsect_firstflwr_both_years_boxplot_L2.png", units="in", width=6, height=6, res=300)
ggplot(trpr_noinsect, aes(x = Subplot_Descriptions, y = min_julian, fill = as.factor(Year))) +
        geom_boxplot(color = "black", outlier.shape = NA) +
        labs(x = "Treatment", y = "T. pratense Average Julian Date of First Flower", fill = "Year") +
        geom_jitter(shape=16, position=position_jitter(0.2)) +
        scale_fill_manual(values = c("ambient" = "darkblue", "drought" = "gray58", "irrigated_control" =
                                             "deepskyblue", "warmed" = "red2", "warmed_drought" = "darkred")) +
        theme(legend.text = element_text(size=16),
              legend.title = element_text(size=16)) +
        scale_x_discrete(labels=c("ambient" = "Ambient",
                                  "drought" = "Drought",
                                  "warmed" = "Warmed",
                                  "warmed_drought" = "Warmed +\n Drought")) +
          scale_fill_manual(values=c("sienna1", "sienna"), # specify colors here
                    labels=c("2021","2022")) + # specify species names here
        theme(legend.position="top")
dev.off
```

```{r}
# delete insecticide treatments
Trpr_noninsect_avg_21 <- avg_first_trpr_21[-c(3:4,8:9),]

# removing treatments we aren't interested in
Trpr_noninsect_21 <- trpr_21 %>%
  filter(!(Subplot_Descriptions=='drought_insecticide' |
                   Subplot_Descriptions=='insecticide' |
                   Subplot_Descriptions=='warmed_drought_insecticide' |
                   Subplot_Descriptions=='warmed_insecticide' |
                   Subplot_Descriptions=='irrigated_control'))
        
# bar plot
png("trpr_noninsect_firstflwr_2021_barplot.png", units="in", width=6, height=6, res=300)
ggplot(Trpr_noninsect_avg_21, aes(x = Subplot_Descriptions, y = avg_min_julian, fill = Subplot_Descriptions)) +
        geom_jitter(shape=16, position=position_jitterdodge(), alpha = 0.6, aes(colour = Subplot_Descriptions)) +
        geom_bar(stat = "identity") +
        geom_errorbar(aes(ymin = avg_min_julian - se, ymax = avg_min_julian + se), width = 0.2,
                         position = "identity") +
        scale_fill_manual(values = c("ambient" = "darkblue", "drought" = "gray58", 
        "irrigated_control" = "deepskyblue", "warmed" = "red2", "warmed_drought" = "darkred")) +
        labs(x = "Treatment", y = "Average Julian Date of First Flower") +
        scale_x_discrete(labels=c("ambient" = "Ambient",
                                  "drought" = "Drought",
                                  "irrigated_control" = "Irrigated \n Control",
                                  "warmed" = "Warmed",
                                  "warmed_drought" = "Warmed +\n Drought")) +
        theme_classic() +
        theme(legend.position = "none")
dev.off

# Box plot
png("trpr_noninsect_firstflwr_2021_boxplot.png", units="in", width=6, height=6, res=300)
ggplot(Trpr_noninsect_21, aes(x = Subplot_Descriptions, y = min_julian, fill = Subplot_Descriptions)) +
        geom_boxplot(color = "black", outlier.shape = NA) +
        labs(x = "Treatment", y = "2021 T. pratense\n Average Julian Date of First Flower", fill = "Subplot_Descriptions") +
        geom_jitter(shape=16, position=position_jitter(0.2)) +
        scale_fill_manual(values = c("ambient" = "darkblue", "drought" = "gray58", "irrigated_control" =
                                             "deepskyblue", "warmed" = "red2", "warmed_drought" = "darkred")) +
        theme(legend.text = element_text(size=16),
              legend.title = element_text(size=16)) +
        scale_x_discrete(labels=c("ambient" = "Ambient",
                                  "drought" = "Drought",
                                  "irrigated_control" = "Irrigated \n Control",
                                  "warmed" = "Warmed",
                                  "warmed_drought" = "Warmed +\n Drought")) +
        theme(legend.position="none")
dev.off
```

2022 Red Clover Plots
```{r}
# removing treatments we aren't interested in
Trpr22_noninsecticide <- trpr_22 %>%
  filter(!(Subplot_Descriptions=='drought_insecticide' |
             Subplot_Descriptions=='insecticide' |
             Subplot_Descriptions=='warmed_drought_insecticide' |
             Subplot_Descriptions=='warmed_insecticide'))

Trpr22_noninsecticide_avg <- avg_first_trpr_22 %>%
  filter(!(Subplot_Descriptions=='drought_insecticide' |
             Subplot_Descriptions=='insecticide' |
             Subplot_Descriptions=='warmed_drought_insecticide' |
             Subplot_Descriptions=='warmed_insecticide'))

# bar plot
png("trpr_noninsect_flwr_2022.png", units="in", width=6, height=6, res=300)
ggplot(Trpr22_noninsecticide_avg, aes(x = Subplot_Descriptions, y = avg_min_julian, fill = Subplot_Descriptions)) +
        geom_jitter(shape=16, position=position_jitterdodge(), alpha = 0.6, aes(colour = Subplot_Descriptions)) +
        geom_bar(stat = "identity") +
        geom_errorbar(aes(ymin = avg_min_julian - se, ymax = avg_min_julian + se), width = 0.2,
                         position = "identity") +
        scale_fill_manual(values = c("ambient" = "darkblue", "drought" = "gray58", 
        "irrigated_control" = "deepskyblue", "warmed" = "red2", "warmed_drought" = "darkred")) +
        labs(x = "Treatment", y = "Average Julian Date of First Flower") +
        scale_x_discrete(limits = level_order, 
                         labels=c("ambient" = "Ambient",
                                  "drought" = "Drought",
                                  "irrigated_control" = "Irrigated \n Control",
                                  "warmed" = "Warmed",
                                  "warmed_drought" = "Warmed +\n Drought")) +
        theme_classic() +
        theme(legend.position = "none")
dev.off()

# Box plot
png("trpr_noninsect_flwr_2022_boxplot.png", units="in", width=6, height=6, res=300)
ggplot(Trpr22_noninsecticide, aes(x = Subplot_Descriptions, y = min_julian, fill = Subplot_Descriptions)) +
        geom_boxplot(color = "black", outlier.shape = NA) +
        labs(x = "Treatment", y = "Average Julian Date of First Flower", fill = "Subplot_Descriptions") +
        geom_jitter(shape=16, position=position_jitter(0.2)) +
        scale_fill_manual(values = c("ambient" = "darkblue", "drought" = "gray58", "irrigated_control" =
                                             "deepskyblue", "warmed" = "red2", "warmed_drought" = "darkred")) +
        theme(legend.text = element_text(size=16),
              legend.title = element_text(size=16)) +
        scale_x_discrete(limits = level_order,
                         labels=c("ambient" = "Ambient",
                                  "drought" = "Drought",
                                  "irrigated_control" = "Irrigated \n Control",
                                  "warmed" = "Warmed",
                                  "warmed_drought" = "Warmed +\n Drought")) +
        theme_classic() +
        theme(legend.position="none")
dev.off()
```

```{r}
trpr_noinsect <- full_join(Trpr22_noninsecticide, Trpr_noninsect_21)
Trpr22_noninsecticide_avg$Year <- 2022
Trpr_noninsect_avg_21$Year <- 2021
trpr_noinsect_avg <- full_join(Trpr22_noninsecticide_avg, Trpr_noninsect_avg_21)
trpr_noinsect_avg <- trpr_noinsect_avg[-c(3,8),]

ggplot(trpr_noinsect_avg, aes(x = Subplot_Descriptions, y = avg_min_julian, fill = as.factor(Year))) +
        geom_bar(position = "dodge", stat = "identity", col = "black") +
        geom_errorbar(aes(ymin = avg_min_julian - se, ymax = avg_min_julian + se), width = 0.2,
                      position = position_dodge(0.9)) +
        labs(x = "Treatment", y = "T. pratense Average Julian Date of First Flower", fill= "Year") +
        scale_x_discrete(limits = level_order,
                         labels=c("ambient" = "Ambient",
                                  "warmed" = "Warmed",
                                  "drought" = "Drought",
                                  "warmed_drought" = "Warmed Drought")) +
        #scale_fill_manual(values=c("#edae49", "#d1495b")) +
        theme(legend.position = "top")
```

