---
title: "T7 warmx soil moisture plots"
author: "Moriah Young"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
---

COLLABORATORS: Jennifer Jones, Tvisha Martin, Grant Flavo
DATA INPUT:  csv from the shared Google drive  
DATA OUTPUT: Code and Rmd are in the scripts folder in Github  
PROJECT: REX

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Clear all existing data
rm(list=ls())

# Load packages
library(bbmle)
library(lmerTest)
library(fitdistrplus)
library(sjPlot)
library(car)
library(emmeans)
library(tidyverse)
library(ggpubr)
library(jtools) #summ 
library(rstatix)
library(RColorBrewer)
library(plotrix)

# Set working directory from .Renviron
dir <- Sys.getenv("DATA_DIR")
list.files(dir)

# Read in data
soil_moisture <- read.csv(file.path(dir, "soil/L1/T7_warmx_soil_moisture_2022_L1.csv")) # 2021 ANPP data
meta <- read.csv(file.path(dir, "REX_warmx_metadata.csv"))

# minor cleaning of data
soil_moisture <- soil_moisture[-c(1,2),]
# change "grav_soil_moisture" column from a character to numeric
soil_moisture$grav_soil_moisture <- as.numeric(as.character(soil_moisture$grav_soil_moisture)) 

# Specifying the order that we want the treatments to be listed in the figures on the x-axis
level_order <- c('irrigated_control', 'ambient', 'drought', 'drought_insecticide', 'insecticide', 'warmed_drought_insecticide', 'warmed_insecticide', 'warmed','warmed_drought')

level_order_1 <- c('irrigated_control', 'ambient', 'drought', 'warmed','warmed_drought')

```


```{r}
# to get average soil moisture per treatment, first sum total soil moisture per plot
# then, take the average of that
soil_moisture_avg <- soil_moisture %>%
  group_by(Unique_ID, Subplot_Description, comments) %>% 
  summarize(sum_soil_moisture = sum(grav_soil_moisture, na.rm = TRUE)) %>% # summing soil moisture per plot
  group_by(Subplot_Description, comments) %>%
  summarize(avg_soil_moisture = mean(sum_soil_moisture, na.rm = TRUE), # taking avg biomass of each treatment
            se = std.error(sum_soil_moisture, na.rm = TRUE))
```

Plot average soil moisture by treatment and drought timing - peak vs post drought
```{r}
png("T7_warmx_avg_soil_moisture_2022.png", units="in", width=14, height=8, res=300)
ggplot(soil_moisture_avg, aes(x = Subplot_Description, y = avg_soil_moisture, fill = Subplot_Description)) +
        geom_bar(stat = "identity") +
        facet_wrap(~comments, scales = "free_x") +
        geom_errorbar(aes(ymin = avg_soil_moisture - se, ymax = avg_soil_moisture + se), width = 0.2,
                         position = "identity") +
        scale_x_discrete(labels=c("ambient" = "Ambient",
                                  "drought" = "Drought",
                                  "warmed" = "Warmed",
                                  "warmed_drought" = "Warmed +\n Drought",
                                  "drought_insecticide" = "Insecticide +\n Drought", 
                                  "insecticide" = "Insecticide", 
                                  "warmed_drought_insecticide" = "Insecticide +\n Warmed +\n Drought", 
                                  "warmed_insecticide" = "Insecticide +\n Warmed",
                                  "Control" = "Irrigated +\n Control")) +
        scale_fill_manual(values = c("ambient" = "darkblue",
                                  "drought" = "gray58",
                                  "warmed" = "red2",
                                  "warmed_drought" = "darkred",
                                  "drought_insecticide" = "dodgerblue4", 
                                  "insecticide" = "sienna1", 
                                  "warmed_drought_insecticide" = "orangered", 
                                  'warmed_insecticide' = "salmon",
                                  "Control" = "deepskyblue")) +
        xlab("Treatment") +
        ylab("Average Soil Moisture") +
        theme(legend.position = "none")
dev.off
```

