---
title: "T7 warmx Microbial Soil GWC plots"
author: "Moriah Young"
date: August 20, 2024, updated November 20, 2024
output: pdf_document
editor_options: 
  chunk_output_type: console
---

COLLABORATORS: Jennifer Jones, Tvisha Martin, Grant Flavo
DATA INPUT:  csv from the shared Google drive  
DATA OUTPUT: Code and Rmd are in the scripts folder in Github  
PROJECT: REX

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Clear all existing data
rm(list=ls())

# Load packages
library(sjPlot)
library(car)
library(tidyverse)
library(ggpubr)
library(jtools) #summ 
library(rstatix)
library(RColorBrewer)
library(plotrix)

# Set working directory from .Renviron
dir <- Sys.getenv("DATA_DIR")
list.files(dir)

# Read in data
soil_gwc <- read.csv(file.path(dir, "soil/L1/T7_warmx_Microbial_Soil_GWC_L1.csv"))
meta <- read.csv(file.path(dir, "REX_warmx_metadata.csv"))

# Specifying the order that we want the treatments to be listed in the figures 
level_order <- c('irrigated_control', 'ambient', 'warmed', 'warmed_insecticide', 'insecticide', 'drought', 'warmed_drought', 'drought_insecticide', 'warmed_drought_insecticide')

level_order_1 <- c('irrigated_control', 'ambient', 'warmed','drought','warmed_drought')

```


```{r}
# select for peak and post drought only for 2021-2023
soil_gwc_1 <- soil_gwc %>% 
        filter(time_of_sampling == "Peak Drought" | time_of_sampling == "Post Drought")

soil_moisture_avg <- soil_gwc_1 %>%
  group_by(Unique_ID, Subplot_Descriptions, time_of_sampling, Year) %>% 
  summarize(sum_soil_moisture = sum(gwc, na.rm = TRUE)) %>% # summing soil moisture per plot
  group_by(Subplot_Descriptions, time_of_sampling, Year) %>%
  summarize(avg_soil_moisture = mean(sum_soil_moisture, na.rm = TRUE), # taking avg biomass of each treatment
            se = std.error(sum_soil_moisture, na.rm = TRUE))

soil_moisture_avg_noinsect <- filter(soil_moisture_avg, Subplot_Descriptions%in%c("Control", "warmed", "ambient", "drought", "warmed_drought")) 
```

2023
```{r}
# bar plot
soil_moisture_avg_23 <- soil_moisture_avg %>% 
        filter(Year == 2023)

ggplot(soil_moisture_avg_23, aes(x = factor(Subplot_Descriptions, levels = level_order), y = avg_soil_moisture, fill = Subplot_Descriptions)) +
        geom_bar(stat = "identity") +
        facet_wrap(~time_of_sampling, scales = "free_x") +
        geom_errorbar(aes(ymin = avg_soil_moisture - se, ymax = avg_soil_moisture + se), width = 0.2,
                         position = "identity") +
        scale_x_discrete(labels=c("ambient" = "Ambient",
                                  "drought" = "Drought",
                                  "warmed" = "Warmed",
                                  "warmed_drought" = "Warmed +\n Drought",
                                  "drought_insecticide" = "Insecticide +\n Drought", 
                                  "insecticide" = "Insecticide", 
                                  "warmed_drought_insecticide" = "Insecticide +\n Warmed +\n Drought", 
                                  "warmed_insecticide" = "Insecticide +\n Warmed",
                                  "irrigated_control" = "Irrigated \n Control")) +
        scale_fill_manual(values = c("ambient" = "darkblue",
                                  "drought" = "gray58",
                                  "warmed" = "red2",
                                  "warmed_drought" = "darkred",
                                  "drought_insecticide" = "dodgerblue4", 
                                  "insecticide" = "sienna1", 
                                  "warmed_drought_insecticide" = "orangered", 
                                  'warmed_insecticide' = "salmon",
                                  "irrigated_control" = "deepskyblue")) +
        xlab("Treatment") +
        ylab("Average Soil Moisture") +
        theme(legend.position = "none")

# boxplot
soil_gwc_23 <- soil_gwc_1 %>% 
        filter(Year == 2023)

ggplot(soil_gwc_23, aes(x = factor(Subplot_Descriptions, levels = level_order), y = gwc, fill = Subplot_Descriptions)) +
        geom_boxplot() +
        facet_wrap(~time_of_sampling, scales = "free_x") +
        scale_x_discrete(labels=c("ambient" = "Ambient",
                                  "drought" = "Drought",
                                  "warmed" = "Warmed",
                                  "warmed_drought" = "Warmed +\n Drought",
                                  "drought_insecticide" = "Insecticide +\n Drought", 
                                  "insecticide" = "Insecticide", 
                                  "warmed_drought_insecticide" = "Insecticide +\n Warmed +\n Drought", 
                                  "warmed_insecticide" = "Insecticide +\n Warmed",
                                  "irrigated_control" = "Irrigated \n Control")) +
        scale_fill_manual(values = c("ambient" = "darkblue",
                                  "drought" = "gray58",
                                  "warmed" = "red2",
                                  "warmed_drought" = "darkred",
                                  "drought_insecticide" = "dodgerblue4", 
                                  "insecticide" = "sienna1", 
                                  "warmed_drought_insecticide" = "orangered", 
                                  'warmed_insecticide' = "salmon",
                                  "irrigated_control" = "deepskyblue")) +
        xlab("Treatment") +
        ylab("Average Soil Moisture") +
        theme(legend.position = "none")
```

2022
```{r}
soil_moisture_avg_22 <- soil_moisture_avg %>% 
        filter(Year == 2022)

ggplot(soil_moisture_avg_22, aes(x = factor(Subplot_Descriptions, levels = level_order), y = avg_soil_moisture, fill = Subplot_Descriptions)) +
        geom_bar(stat = "identity") +
        facet_wrap(~time_of_sampling, scales = "free_x") +
        geom_errorbar(aes(ymin = avg_soil_moisture - se, ymax = avg_soil_moisture + se), width = 0.2,
                         position = "identity") +
        scale_x_discrete(labels=c("ambient" = "Ambient",
                                  "drought" = "Drought",
                                  "warmed" = "Warmed",
                                  "warmed_drought" = "Warmed +\n Drought",
                                  "drought_insecticide" = "Insecticide +\n Drought", 
                                  "insecticide" = "Insecticide", 
                                  "warmed_drought_insecticide" = "Insecticide +\n Warmed +\n Drought", 
                                  "warmed_insecticide" = "Insecticide +\n Warmed",
                                  "irrigated_control" = "Irrigated \n Control")) +
        scale_fill_manual(values = c("ambient" = "darkblue",
                                  "drought" = "gray58",
                                  "warmed" = "red2",
                                  "warmed_drought" = "darkred",
                                  "drought_insecticide" = "dodgerblue4", 
                                  "insecticide" = "sienna1", 
                                  "warmed_drought_insecticide" = "orangered", 
                                  'warmed_insecticide' = "salmon",
                                  "irrigated_control" = "deepskyblue")) +
        xlab("Treatment") +
        ylab("Average Soil Moisture") +
        theme(legend.position = "none")
```

2021
```{r}
soil_moisture_avg_21 <- soil_moisture_avg %>% 
        filter(Year == 2021)

ggplot(soil_moisture_avg_21, aes(x = factor(Subplot_Descriptions, levels = level_order), y = avg_soil_moisture, fill = Subplot_Descriptions)) +
        geom_bar(stat = "identity") +
        facet_wrap(~time_of_sampling, scales = "free_x") +
        geom_errorbar(aes(ymin = avg_soil_moisture - se, ymax = avg_soil_moisture + se), width = 0.2,
                         position = "identity") +
        scale_x_discrete(labels=c("ambient" = "Ambient",
                                  "drought" = "Drought",
                                  "warmed" = "Warmed",
                                  "warmed_drought" = "Warmed +\n Drought",
                                  "drought_insecticide" = "Insecticide +\n Drought", 
                                  "insecticide" = "Insecticide", 
                                  "warmed_drought_insecticide" = "Insecticide +\n Warmed +\n Drought", 
                                  "warmed_insecticide" = "Insecticide +\n Warmed",
                                  "irrigated_control" = "Irrigated \n Control")) +
        scale_fill_manual(values = c("ambient" = "darkblue",
                                  "drought" = "gray58",
                                  "warmed" = "red2",
                                  "warmed_drought" = "darkred",
                                  "drought_insecticide" = "dodgerblue4", 
                                  "insecticide" = "sienna1", 
                                  "warmed_drought_insecticide" = "orangered", 
                                  'warmed_insecticide' = "salmon",
                                  "irrigated_control" = "deepskyblue")) +
        xlab("Treatment") +
        ylab("Average Soil Moisture") +
        theme(legend.position = "none")
```







# ARCHIVE BELOW
```{r}
soil_moisture_22 <- soil_gwc %>% 
        filter(Year == 2022)

# to get average soil moisture per treatment, first sum total soil moisture per plot
# then, take the average of that
soil_moisture_avg <- soil_moisture_22 %>%
  group_by(Unique_ID, Subplot_Description, time_of_sampling) %>% 
  summarize(sum_soil_moisture = sum(gwc, na.rm = TRUE)) %>% # summing soil moisture per plot
  group_by(Subplot_Description, time_of_sampling) %>%
  summarize(avg_soil_moisture = mean(sum_soil_moisture, na.rm = TRUE), # taking avg biomass of each treatment
            se = std.error(sum_soil_moisture, na.rm = TRUE))

soil_moisture_avg_noinsect <- filter(soil_moisture_avg, Subplot_Description%in%c("Control", "warmed", "ambient", "drought", "warmed_drought")) 
        
```

Plot average soil moisture by treatment and drought timing - peak vs post drought
```{r}
png("T7_warmx_avg_soil_moisture_2022.png", units="in", width=14, height=8, res=300)
ggplot(soil_moisture_avg, aes(x = factor(Subplot_Description, levels = level_order), y = avg_soil_moisture, fill = Subplot_Description)) +
        geom_bar(stat = "identity") +
        facet_wrap(~time_of_sampling, scales = "free_x") +
        geom_errorbar(aes(ymin = avg_soil_moisture - se, ymax = avg_soil_moisture + se), width = 0.2,
                         position = "identity") +
        scale_x_discrete(labels=c("ambient" = "Ambient",
                                  "drought" = "Drought",
                                  "warmed" = "Warmed",
                                  "warmed_drought" = "Warmed +\n Drought",
                                  "drought_insecticide" = "Insecticide +\n Drought", 
                                  "insecticide" = "Insecticide", 
                                  "warmed_drought_insecticide" = "Insecticide +\n Warmed +\n Drought", 
                                  "warmed_insecticide" = "Insecticide +\n Warmed",
                                  "Control" = "Irrigated \n Control")) +
        scale_fill_manual(values = c("ambient" = "darkblue",
                                  "drought" = "gray58",
                                  "warmed" = "red2",
                                  "warmed_drought" = "darkred",
                                  "drought_insecticide" = "dodgerblue4", 
                                  "insecticide" = "sienna1", 
                                  "warmed_drought_insecticide" = "orangered", 
                                  'warmed_insecticide' = "salmon",
                                  "Control" = "deepskyblue")) +
        xlab("Treatment") +
        ylab("Average Soil Moisture") +
        theme(legend.position = "none")
dev.off()
```

Excluding insecticide plots
```{r}
png("T7_warmx_avg_soil_moisture_noinsect_2022.png", units="in", width=12, height=8, res=300)
ggplot(soil_moisture_avg_noinsect, aes(x = factor(Subplot_Description, levels = level_order), y = avg_soil_moisture, fill = Subplot_Description)) +
        geom_bar(stat = "identity") +
        facet_wrap(~time_of_sampling, scales = "free_x") +
        geom_errorbar(aes(ymin = avg_soil_moisture - se, ymax = avg_soil_moisture + se), width = 0.2,
                         position = "identity") +
        scale_x_discrete(labels=c("ambient" = "Ambient",
                                  "drought" = "Drought",
                                  "warmed" = "Warmed",
                                  "warmed_drought" = "Warmed +\n Drought",
                                  "Control" = "Irrigated \n Control")) +
        scale_fill_manual(values = c("ambient" = "#a6bddb",
                                  "drought" = "#2F4F4f",
                                  "warmed" = "#8B6914",
                                  "warmed_drought" = "#9D422E",
                                  "Control" = "deepskyblue")) +
        xlab("Treatment") +
        ylab("Average Gravimetric Soil Water Content") +
        theme_bw() +
        theme(legend.position = "none",
              strip.text.x = element_text(size = 15),
              axis.text.x=element_text(size=15),
              axis.text.y=element_text(size=15),
              axis.title.y = element_text(size=15),
              axis.title.x = element_blank())
dev.off()

soil_moisture_avg_noinsect$time_of_sampling <- as.factor(soil_moisture_avg_noinsect$time_of_sampling)

png("T7_warmx_avg_soil_moisture_noinsect_2022_point.png", units="in", width=12, height=8, res=300)
ggplot(soil_moisture_avg_noinsect, aes(x = factor(Subplot_Description, levels = level_order), y = avg_soil_moisture, color = Subplot_Description, shape = time_of_sampling)) +
        geom_pointrange(aes(ymin=avg_soil_moisture - se, ymax=avg_soil_moisture + se), size = 1.5) +
         scale_shape_manual(values = c("Peak Drought" = 16, "Post Drought" = 17)) +
         scale_x_discrete(labels=c("ambient" = "Ambient",
                                  "drought" = "Drought",
                                  "warmed" = "Warmed",
                                  "warmed_drought" = "Warmed +\n Drought",
                                  "Control" = "Irrigated \n Control")) +
        scale_color_manual(values = c("ambient" = "#a6bddb",
                                  "drought" = "#2F4F4f",
                                  "warmed" = "#8B6914",
                                  "warmed_drought" = "#9D422E",
                                  "Control" = "deepskyblue"),
                           labels=c("ambient" = "Ambient",
                                  "drought" = "Drought",
                                  "warmed" = "Warmed",
                                  "warmed_drought" = "Warmed + Drought",
                                  "Control" = "Irrigated Control")) +
        labs(y="Average Gravimetric Soil Water Content", 
             x="Treatment", 
             color = "Treatment",
             shape = "Time of Sampling") +
                theme_bw() +
        theme(axis.title = element_text(size=15),
              axis.text = element_text(size=15))
dev.off()
```

