---
title: "T7 warmx Trpr ANPP 2022 Plots & Analysis"
author: "Adrian Noecker"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

COLLABORATORS: Kara Dobson, Phoebe Zarnetske, Mark Hammond, Moriah Young
DATA INPUT:  csv from the shared Google drive  
DATA OUTPUT: Code and Rmd are in the scripts folder in Github  
PROJECT: REX


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Clear all existing data
rm(list=ls())

# Load packages
library(tidyverse)
library(plotrix)
library(rstatix)
library(car)
library(lme4)
library(emmeans)
library(lmerTest)

# Set working directory from .Renviron
dir <- Sys.getenv("DATA_DIR")
list.files(dir)

# Read in data
anpp22 <- read.csv(file.path(dir, "T7_ANPP/L1/T7_warmx_ANPP_2022_L1.csv")) # 2022 ANPP data
meta <- read.csv(file.path(dir, "REX_warmx_metadata.csv"))

#making order for graph
level_order_1 <- c('irrigated_control', 'ambient', 'drought', 'warmed','warmed_drought')

# changing column name
names(anpp22)[3] <- "Biomass_g"

```

selecting for wanted treatments and species + calculating avg

```{r}
# selecting for only red clover
trfpr_anpp <- anpp22 %>% 
  filter(Species_Code == 'TRFPR')
  
# removing unwanted treatments
trfpr_anpp_noinsect <- trfpr_anpp %>%
  filter(!(Subplot_Descriptions=='drought_insecticide' |
             Subplot_Descriptions=='insecticide' |
             Subplot_Descriptions=='warmed_drought_insecticide' |
             Subplot_Descriptions=='warmed_insecticide'))

# to get average biomass per treatment, first sum total biomass per plot
# then, take the average of hat
anpp22_avg <- trfpr_anpp_noinsect %>%
  group_by(Field_Loc_Code, Subplot_Descriptions) %>% 
  summarize(sum_biomass = sum(Biomass_g, na.rm = TRUE)) # summing biomass per plot
  
anpp_avg <- anpp22_avg %>%   
  group_by(Subplot_Descriptions) %>%
  summarize(avg_biomass = mean(sum_biomass, na.rm = TRUE), # taking avg biomass of each treatment
            se = std.error(sum_biomass, na.rm = TRUE))
```

making plots

```{r}
#bar graph
png("avg_trpr_anpp_no_insect_2022_barplot.png", units="in", width=6, height=6, res=300)
ggplot(anpp_avg, aes(x = Subplot_Descriptions, y = avg_biomass, fill = Subplot_Descriptions)) +
        geom_bar(stat = "identity") +
        geom_errorbar(aes(ymin = avg_biomass - se, ymax = avg_biomass + se), width = 0.2,
                         position = "identity") +
        scale_fill_manual(values = c("ambient" = "#a6bddb", "drought" = "#2F4F4f", 
        "irrigated_control" = "#6B8E23", "warmed" = "#8B6914", "warmed_drought" = "#9D422E")) +
        ylab(bquote("2022 Red Clover Average Biomass" ('g/0.20m'^2))) +
        xlab("Treatment") +
        scale_x_discrete(limits = level_order_1, labels=c("ambient" = "Ambient",
                                  "drought" = "Drought",
                                  "warmed" = "Warmed",
                                  "warmed_drought" = "Warmed +\n Drought",
                                  "irrigated_control" = "Irrigated \n Control")) +
        theme(legend.position = "none")
dev.off

# boxplot
png("avg_trpr_anpp_no_insect_2022_boxplot.png", units="in", width=8, height=6, res=300)
ggplot(trfpr_anpp_noinsect, aes(x = Subplot_Descriptions, y = Biomass_g, fill = Subplot_Descriptions)) +
        geom_boxplot(color = "black", outlier.shape = NA, show.legend = FALSE) +
        scale_fill_manual(values = c("ambient" = "#a6bddb", "drought" = "#2F4F4f", 
        "irrigated_control" = "#6B8E23", "warmed" = "#8B6914", "warmed_drought" = "#9D422E")) +
        ylab(bquote("Average Biomass " ('g/0.20m'^2))) +
        xlab("Treatment") +
        scale_x_discrete(limits = level_order_1, labels=c("ambient" = "Ambient",
                                  "drought" = "Drought",
                                  "irrigated_control" = "Irrigated \n Control",
                                  "warmed" = "Warmed",
                                  "warmed_drought" = "Warmed +\n Drought")) +
                        theme_bw() +
        theme(axis.title = element_text(size=17),
              axis.text = element_text(size=15))
dev.off()
```

Data Exploration
```{r}
# checking raw data
hist(trfpr_anpp_noinsect$Biomass_g) # raw data right skewed
qqnorm(trfpr_anpp_noinsect$Biomass_g)

# checking model with log transformation
m1 <- lm(log(Biomass_g) ~ Subplot_Descriptions, data=trfpr_anpp_noinsect)
hist(resid(m1))
qqnorm(resid(m1))
shapiro.test(resid(m1)) # still not normal p=0.02

#checking with square transformation
m2 <- lm(sqrt(Biomass_g) ~ Subplot_Descriptions, data=trfpr_anpp_noinsect)
hist(resid(m2)) # histogram right skewed
qqnorm(resid(m2))
shapiro.test(resid(m2)) #(p=0.75)
leveneTest(resid(m2) ~ Subplot_Descriptions, data = trfpr_anpp_noinsect) # p=0.36 -- homogeneity of variance? yes if p >0.05

#models
m3 <- lmer(sqrt(Biomass_g) ~ Subplot_Descriptions + (1|Rep/Footprint_Location), data=trfpr_anpp_noinsect, REML=F)
anova(m3) #p=0.068
summary(m3)

# code below lets you look at pairwise comparisons between the treatments
emmeans(m3, list(pairwise ~ Subplot_Descriptions), adjust = "tukey")

```

