---
title: "REX: Soca Biomass Analysis"
author: "Moriah Young"
date: "February 2024"
output: pdf_document
editor_options: 
  chunk_output_type: console
---
COLLABORATORS: Emily Parker, Kara Dobson, Phoebe Zarnetske, Mark Hammond
DATA INPUT: L1 csv from the shared Google drive  
DATA OUTPUT: L2 csv and Code and Rmd are in the scripts folder in Github  
PROJECT: REX - goldenrod gall project
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Clear all existing data
rm(list=ls())

# Load packages
library(lmerTest)
library(fitdistrplus)
library(sjPlot)
library(tidyverse)
library(car)
library(emmeans)
library(bbmle)
library(multcomp)
library(knitr)
library(see)
library(performance)

# Set working directory from .Renviron
dir <- Sys.getenv("DATA_DIR")
list.files(dir)

## Read in data
biomass <- read.csv(file.path(dir, "/T7_warmx_plant_traits/L1/T7_warmx_soca_biomass_L1.csv"))
biomass$Year <- as.factor(biomass$Year)
```

Data Exploration
```{r}
# The first thing we do is check the distribution of the raw data
# We're checking for a normal distribution; the distribution of the raw data
# doesn't matter as much as the distribution of a model's residuals (which we'll also check),
# but its a good way to get a glimpse of how the data look
descdist(biomass$Biomass, discrete = FALSE) # checks what type of distribution your data matches
hist(biomass$Biomass) # should be a bell curve if normal
qqnorm(biomass$Biomass) # should be a straight diagonal line if normal
shapiro.test(biomass$Biomass) # p > 0.05 if normal
# making a model to test distribution of model residuals
raw.data.test <- lm(Biomass ~ Climate_Treatment * Galling_Status, data=biomass) # testing model
hist(resid(raw.data.test)) # checking model residuals
shapiro.test(resid(raw.data.test))
# looks pretty good, going to try some transformations but might not need them

# log normal transformation
biomass$log_biomass <- log(biomass$Biomass)
descdist(biomass$log_biomass, discrete = FALSE)
hist(biomass$log_biomass)
qqnorm(biomass$log_biomass)
shapiro.test(biomass$log_biomass) # looks good
# making a model to test distribution of model residuals w/ log transformation
raw.data.test.log <- lm(log_biomass ~ Climate_Treatment * Galling_Status, data=biomass) # testing model
hist(resid(raw.data.test.log)) # checking model residuals
shapiro.test(resid(raw.data.test.log))
# better - going with log transformation

# square root transformation
biomass$sqrt_biomass <- sqrt(biomass$Biomass)
descdist(biomass$sqrt_biomass, discrete = FALSE)
hist(biomass$sqrt_biomass)
qqnorm(biomass$sqrt_biomass)
shapiro.test(biomass$sqrt_biomass) # looks good
# making a model to test distribution of model residuals w/ sqrt transformation
raw.data.test.sqrt <- lm(sqrt_biomass ~ Climate_Treatment * Galling_Status, data=biomass) # testing model
hist(resid(raw.data.test.sqrt)) # checking model residuals
shapiro.test(resid(raw.data.test.sqrt))

# going with sqrt root transformation
```

Assumption checking
```{r}
# in the assumption checking, we're making sure that our full model meets the assumptions of the model.
# the model below is the model structure we can use for all response variables; its testing to see
# if there is 1. an effect of climate treatment on biomass, 2. an effect of galling status on height, and 3. does the
# effect of climate on height depend on galling status. Subplot nested within footprint nested within rep is used as our # random effect to account for variation between plots. Year is also included as a random effect to account for variation # between years.
m1 <- lmer(sqrt_biomass ~ Climate_Treatment * Galling_Status + (1|Rep/Footprint/Subplot) + (1|Year), data = biomass, REML=F)

# Check Assumptions:
# (1) Linearity: if covariates are not categorical
# (2) Homogeneity: Need to Check by plotting residuals vs predicted values.
plot(m1, main = "Soca Biomass")
# Homogeneity of variance looks a bit off (increasing variance in resids does increase with fitted values)
# Check for homogeneity of variances (true if p>0.05). If the result is not significant, the assumption of equal variances (homoscedasticity) is met (no significant difference between the group variances).
leveneTest(residuals(m1) ~ biomass$Climate_Treatment) # not met
leveneTest(residuals(m1) ~ biomass$Galling_Status) # met
# (3) Normality of error term: need to check by histogram, QQplot of residuals, could do Kolmogorov-Smirnov test.
# Check for normal residuals
qqPlot(resid(m1), main = "Soca biomass")
hist(residuals(m1), main = "Soca biomass")
shapiro.test(resid(m1))
outlierTest(m1) # checking for outliers - none
```

Checking model results
```{r}
summary(m1)
anova(m1)

emmip(m1, Climate_Treatment~Galling_Status)

# re-set the reference level for diff. comparisons
biomass <- within(biomass, Climate_Treatment <- relevel(factor(Climate_Treatment), ref = "Ambient"))
m1 <- lmer(sqrt_biomass ~ Climate_Treatment * Galling_Status + (1|Rep/Footprint/Subplot) + (1|Year), data = biomass, REML=F)
summary(m1)
anova(m1)

# Pairwise comparisons for climate treatments
# back-transforming - A vs. W
(2.02785)^2-((2.02785-0.42931)^2) # 1.556845 - warmed plants weighed ~1.56 g more than ambient
# back-transforming - A vs. WD
(2.02785)^2-((2.02785-0.53658)^2) # 1.888289 - warmed + drought plants weighed ~1.89 g more than ambient

biomass <- within(biomass, Climate_Treatment <- relevel(factor(Climate_Treatment), ref = "Ambient Drought"))
m1 <- lmer(sqrt_biomass ~ Climate_Treatment * Galling_Status + (1|Rep/Footprint/Subplot) + (1|Year), data = biomass, REML=F)
summary(m1)
anova(m1)

# Pairwise comparisons for climate treatments
# back-transforming - D vs. W
(2.11198)^2-((2.11198-0.34518)^2) # 1.338877 - warmed plants weighed ~1.34 g more than droughted plants

# Pairwise comparisons for climate treatments
# back-transforming - D vs. WD
(2.11198)^2-((2.11198-0.45245)^2) # 1.70642 - warmed + drought plants weighed ~1.71 g more than droughted plants

biomass <- within(biomass, Climate_Treatment <- relevel(factor(Climate_Treatment), ref = "Ambient"))
m1 <- lmer(sqrt_biomass ~ Climate_Treatment * Galling_Status + (1|Rep/Footprint/Subplot) + (1|Year), data = biomass, REML=F)
summary(m1)
anova(m1)

# Pairwise comparisons for non-galled vs galled
summary(m1)

# back-transforming - galled vs. non-galled
(2.02785)^2-((2.02785-(-0.02733))^2) # -0.1115892 - non-galled plants weighed 0.11 g less than galled plants

# contrasts for treatment
contrast1 <- contrast(emmeans(m1, ~Climate_Treatment), "pairwise", simple = "each", combine = F, adjust = "mvt", type = "response")
contrast1
result1 = as.data.frame(contrast1)
result1 <- result1 %>% mutate_if(is.numeric, round, digits=2)
kable(result1) %>% kableExtra::kable_styling() # table

# contrasts for galling status
contrast2 <- contrast(emmeans(m1, ~Galling_Status), "pairwise", simple = "each", combine = F, adjust = "mvt")
contrast2
result2 = as.data.frame(contrast2)
result2 <- result2 %>% mutate_if(is.numeric, round, digits=2)
kable(result2) %>% kableExtra::kable_styling() # table

# contrasts for interaction - treatment * galling status
contrast3 <- contrast(emmeans(m1, ~Climate_Treatment*Galling_Status), "pairwise", simple = "each", combine = F, adjust = "mvt")
contrast3
result3 = as.data.frame(contrast3)
result3 <- result3 %>% mutate_if(is.numeric, round, digits=2)
kable(result3) %>% kableExtra::kable_styling() # table

# make model table for supp
kable(anova(m1), digits = 3) %>% kableExtra::kable_styling()
```


