---
title: "T7 warmx Trpr CN 2022 Analysis"
author: "Moriah Young"
date: "2023-07-19"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Clear all existing data
rm(list=ls())

# load packages
library(tidyverse)
library(lmerTest)
library(car)
library(bbmle)
library(sjPlot)
library(emmeans)
library(stats)
library(plotrix)
library(fitdistrplus) # descdist() function

# Set working directory from .Renviron
dir <- Sys.getenv("DATA_DIR")
list.files(dir)

# Read in data
trpr_cn <- read.csv(file.path(dir, "T7_warmx_plant_traits/L1/T7_warmx_CN_Trpr_2022_L1.csv")) # 2022 CN Trpr data

alive <- subset(trpr_cn, Species_Code == "Trfpr (alive)")
dead <- subset(trpr_cn, Species_Code == "Trfpr (dead)")

# calculating C:N ratio
trpr_cn$CN_ratio <- trpr_cn$Carbon/trpr_cn$Nitrogen

```

```{r}
#### Data exploration ###
# checking raw data
hist(trpr_cn$Carbon)
qqnorm(trpr_cn$Carbon)

# Exploring distributions for these data:
descdist(trpr_cn$Carbon, discrete = FALSE)

# checking model with log transformation (untransformed data was right skewed)
# is it normally distributed? no
m1 <- lm(Carbon ~ Subplot_Descriptions, data=trpr_cn)
outlierTest(m1)
hist(resid(m1))
qqnorm(resid(m1))
shapiro.test(resid(m1))
# homogeneity of variance? yes if p >0.05 (no significant difference between the group variances)
leveneTest(residuals(m1) ~ trpr_cn$Subplot_Descriptions)

```

Model Exploration
```{r}
# overall biomass
m_plot1 <- lmer(Carbon ~ Subplot_Descriptions + (1|Rep/Footprint_Location), data=trpr_cn, REML=F)
m_plot2 <- lmer(Carbon ~ Subplot_Descriptions + Species_Code + (1|Rep/Footprint_Location), data=trpr_cn, REML=F)
m_plot3 <- lmer(Carbon ~ Subplot_Descriptions * Species_Code + (1|Rep/Footprint_Location), data=trpr_cn, REML=F)
anova(m_plot1,m_plot2)
anova(m_plot2,m_plot3)
AICctab(m_plot1, m_plot2, m_plot3)
hist(resid(m_plot3))
shapiro.test(resid(m_plot3))
anova(m_plot3)
summary(m_plot3)
emmeans(m_plot3, list(pairwise ~ Subplot_Descriptions), adjust = "tukey")
emmeans(m_plot3, list(pairwise ~ Subplot_Descriptions * Species_Code))

```

Carbon - alive samples
```{r}
#### Data exploration ###
# checking raw data
hist(alive$Carbon)
qqnorm(alive$Carbon)

# Exploring distributions for these data:
descdist(alive$Carbon, discrete = FALSE)

# checking model with log transformation (untransformed data was right skewed)
# is it normally distributed? no
m1 <- lm(Carbon ~ Subplot_Descriptions, data=alive)
outlierTest(m1)
hist(resid(m1))
qqnorm(resid(m1))
shapiro.test(resid(m1)) # yes, normal
# homogeneity of variance? yes if p >0.05 (no significant difference between the group variances)
leveneTest(residuals(m1) ~ alive$Subplot_Descriptions)

```

Model Exploration
```{r}
m_plot1 <- lmer(Carbon ~ Subplot_Descriptions + (1|Rep/Footprint_Location), data=alive, REML=F)
anova(m_plot1)
hist(resid(m_plot1))
shapiro.test(resid(m_plot1))
anova(m_plot1)
summary(m_plot1)
emmeans(m_plot3, list(pairwise ~ Subplot_Descriptions), adjust = "tukey")
```

```{r}
# Scatter Plot
#png("rex_scatter_biomass_nitrogen_22.png", units="in", width=8, height=8, res=300)
ggplot(alive, aes(x = Nitrogen, y = Dried_Plant_Biomass_gram, group = Subplot_Descriptions, color = Subplot_Descriptions)) +
   geom_point(size = 4) +
   scale_color_manual(name="Treatment",
                      values = c("#a6bddb", "#2F4F4f", "#8B6914", "#9D422E", "#6B8E23"),
                      labels = c("Ambient","Drought","Warmed", "Warmed Drought", "Irrigated Control")) +
        xlab("Nitrogen Content (%)") +
        ylab(bquote("2022 Red Clover Avg Biomass" ('g/0.20m'^2))) +
   theme_bw() +
   theme(axis.title = element_text(size=17),
         axis.text = element_text(size=15))
dev.off()

#Correlation coefficient 
coefficient <- cor.test(alive$Dried_Plant_Biomass_gram., alive$Nitrogen)
coefficient$estimate
 
#Regression Plot
png("rex_regression_biomass_nitrogen_2022.png", units="in", width=8, height=6, res=300)
ggplot(alive, aes(x = Nitrogen, y = Dried_Plant_Biomass_gram, color = Subplot_Descriptions)) + 
         geom_point(size = 3) +
         stat_smooth(method = "lm", col = "red") +
         xlab("Nitrogen Content (%)") +
         ylab(bquote("2022 Red Clover Avg Alive Biomass" ('g/0.20m'^2))) +
         scale_color_manual(name="Treatment",
                      values = c("#a6bddb", "#2F4F4f", "#8B6914", "#9D422E", "#6B8E23"),
                      labels = c("Ambient","Drought","Warmed", "Warmed Drought", "Irrigated Control"))
dev.off()

#Model
model1=lmer(Nitrogen ~ Dried_Plant_Biomass_gram. + Subplot_Descriptions + (1|Rep/Footprint_Location), data = alive)
plot(model1)
summary(model1)
anova(model1)
emmeans(model1, list(pairwise ~ Subplot_Descriptions), adjust = "tukey")
 
#Regression Plot
ggplotRegression <- function (fit) {
 
ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
   geom_point() +
   stat_smooth(method = "lm", col = "red") +
   labs(title = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 5),
                      "Intercept =",signif(fit$coef[[1]],5 ),
                      " Slope =",signif(fit$coef[[2]], 5),
                      " P =",signif(summary(fit)$coef[2,4], 5)))
 }
fit1 <- lm(Nitrogen ~ Dried_Plant_Biomass_gram + Subplot_Descriptions + (1|Rep/Footprint_Location), data = alive)
ggplotRegression(fit1) # no correlation between soil moisture and Trfpr biomass
```

Nitrogen - alive samples
```{r}
#### Data exploration ###
# checking raw data
hist(alive$Nitrogen)
qqnorm(alive$Nitrogen)

# Exploring distributions for these data:
descdist(alive$Nitrogen, discrete = FALSE)

# checking model with log transformation (untransformed data was right skewed)
# is it normally distributed? no
m1 <- lm(Nitrogen ~ Subplot_Descriptions, data=alive)
outlierTest(m1)
hist(resid(m1))
qqnorm(resid(m1))
shapiro.test(resid(m1)) # yes, very close to normal at least
# homogeneity of variance? yes if p >0.05 (no significant difference between the group variances)
leveneTest(residuals(m1) ~ alive$Subplot_Descriptions)

```

Model Exploration
```{r}
m_plot1 <- lmer(Nitrogen ~ Subplot_Descriptions + (1|Rep/Footprint_Location), data=alive, REML=F)
hist(resid(m_plot1))
shapiro.test(resid(m_plot1))
anova(m_plot1)
summary(m_plot1)
emmeans(m_plot1, list(pairwise ~ Subplot_Descriptions), adjust = "tukey")
```

Alive and dead combined
```{r}
#### Data exploration ###
# checking raw data
hist(trpr_cn$Nitrogen)
qqnorm(trpr_cn$Nitrogen)

# Exploring distributions for these data:
descdist(trpr_cn$Nitrogen, discrete = FALSE)

# checking model with log transformation (untransformed data was right skewed)
# is it normally distributed? no
m1 <- lm(Nitrogen ~ Subplot_Descriptions, data=trpr_cn)
outlierTest(m1)
hist(resid(m1))
qqnorm(resid(m1))
shapiro.test(resid(m1))
# homogeneity of variance? yes if p >0.05 (no significant difference between the group variances)
leveneTest(residuals(m1) ~ trpr_cn$Subplot_Descriptions)

m_plot1 <- lmer(Nitrogen ~ Subplot_Descriptions + Dried_Plant_Biomass_gram + (1|Rep/Footprint_Location), data=trpr_cn, REML=F)
hist(resid(m_plot1))
shapiro.test(resid(m_plot1))
summary(m_plot1)
anova(m_plot1)
emmeans(m_plot1, list(pairwise ~ Subplot_Descriptions), adjust = "tukey")
```

# Regression Plot - Nitrogen & Biomass
```{r}
#Correlation coefficient 
coefficient <- cor.test(trpr_cn$Dried_Plant_Biomass_gram, trpr_cn$Nitrogen)
coefficient$estimate
 
#Regression Plot
png("rex_regression_biomass_nitrogen_2022.png", units="in", width=8, height=6, res=300)
nitrogen <- ggplot(trpr_cn, aes(x = Nitrogen, y = Dried_Plant_Biomass_gram, color = Subplot_Descriptions)) + 
         geom_point(size = 2) +
         stat_smooth(method = "lm", col = "red") +
         xlab("Nitrogen (%)") +
         ylab(NULL) +
         scale_color_manual(name="Treatment",
                      values = c("#a6bddb", "#2F4F4f", "#8B6914", "#9D422E", "#6B8E23"),
                      labels = c("Ambient","Drought","Warmed", "Warmed Drought", "Irrigated Control")) +
        theme_bw() +
        theme(axis.title = element_text(size=17),
              axis.text = element_text(size=15))
dev.off()

#Model
model1=lmer(Nitrogen ~ Dried_Plant_Biomass_gram + Subplot_Descriptions + (1|Rep/Footprint_Location), data = trpr_cn)
plot(model1)
summary(model1)
anova(model1)
emmeans(model1, list(pairwise ~ Subplot_Descriptions), adjust = "tukey")
 
#Regression Plot
ggplotRegression <- function (fit) {
 
ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
   geom_point() +
   stat_smooth(method = "lm", col = "red") +
   labs(title = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 5),
                      "Intercept =",signif(fit$coef[[1]],5 ),
                      " Slope =",signif(fit$coef[[2]], 5),
                      " P =",signif(summary(fit)$coef[2,4], 5)))
 }
fit1 <- lm(Nitrogen ~ Dried_Plant_Biomass_gram + Subplot_Descriptions + (1|Rep/Footprint_Location), data = trpr_cn)
ggplotRegression(fit1) # no correlation between soil moisture and Trfpr biomass
```

# Regression Plot - Carbon & Biomass
```{r}
#Correlation coefficient 
coefficient <- cor.test(trpr_cn$Dried_Plant_Biomass_gram, trpr_cn$Carbon)
coefficient$estimate
 
#Regression Plot
png("rex_regression_biomass_carbon_2022.png", units="in", width=8, height=6, res=300)
carbon <- ggplot(trpr_cn, aes(x = Carbon, y = Dried_Plant_Biomass_gram, color = Subplot_Descriptions)) + 
         geom_point(size = 2) +
         stat_smooth(method = "lm", col = "red") +
         xlab("Carbon (%)") +
         ylab(bquote("Biomass "('g/0.20m'^2))) +
         scale_color_manual(name="Treatment",
                      values = c("#a6bddb", "#2F4F4f", "#8B6914", "#9D422E", "#6B8E23"),
                      labels = c("Ambient","Drought","Warmed", "Warmed Drought", "Irrigated Control")) +
                theme_bw() +
        theme(axis.title = element_text(size=17),
              axis.text = element_text(size=15))
dev.off()

#Model
model1=lmer(Carbon ~ Dried_Plant_Biomass_gram + Subplot_Descriptions + (1|Rep/Footprint_Location), data = trpr_cn)
plot(model1)
summary(model1)
anova(model1)
emmeans(model1, list(pairwise ~ Subplot_Descriptions), adjust = "tukey")
 
#Regression Plot
ggplotRegression <- function (fit) {
 
ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
   geom_point() +
   stat_smooth(method = "lm", col = "red") +
   labs(title = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 5),
                      "Intercept =",signif(fit$coef[[1]],5 ),
                      " Slope =",signif(fit$coef[[2]], 5),
                      " P =",signif(summary(fit)$coef[2,4], 5)))
 }
fit1 <- lm(Carbon ~ Dried_Plant_Biomass_gram + Subplot_Descriptions + (1|Rep/Footprint_Location), data = trpr_cn)
ggplotRegression(fit1) # no correlation between soil moisture and Trfpr biomass
```

# Regression Plot - C:N ratio & biomass
```{r}
#Correlation coefficient 
coefficient <- cor.test(trpr_cn$Dried_Plant_Biomass_gram, trpr_cn$CN_ratio)
coefficient$estimate
 
#Regression Plot
png("rex_regression_biomass_cn_ratio_2022.png", units="in", width=8, height=6, res=300)
ratio <- ggplot(trpr_cn, aes(x = CN_ratio, y = Dried_Plant_Biomass_gram, color = Subplot_Descriptions)) + 
         geom_point(size = 2) +
         stat_smooth(method = "lm", col = "red") +
         xlab("C:N Ratio") +
         ylab(NULL) +
         scale_color_manual(name="Treatment",
                      values = c("#a6bddb", "#2F4F4f", "#8B6914", "#9D422E", "#6B8E23"),
                      labels = c("Ambient","Drought","Warmed", "Warmed Drought", "Irrigated Control")) +
                theme_bw() +
        theme(axis.title = element_text(size=17),
              axis.text = element_text(size=15))
dev.off()

#Model
model1=lmer(CN_ratio ~ Dried_Plant_Biomass_gram + Subplot_Descriptions + (1|Rep/Footprint_Location), data = trpr_cn)
plot(model1)
summary(model1)
anova(model1)
emmeans(model1, list(pairwise ~ Subplot_Descriptions), adjust = "tukey")
 
#Regression Plot
ggplotRegression <- function (fit) {
 
ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
   geom_point() +
   stat_smooth(method = "lm", col = "red") +
   labs(title = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 5),
                      "Intercept =",signif(fit$coef[[1]],5 ),
                      " Slope =",signif(fit$coef[[2]], 5),
                      " P =",signif(summary(fit)$coef[2,4], 5)))
 }
fit1 <- lm(CN_ratio ~ Dried_Plant_Biomass_gram + Subplot_Descriptions + (1|Rep/Footprint_Location), data = trpr_cn)
ggplotRegression(fit1) # no correlation between soil moisture and Trfpr biomass
```

Combining Regression Plots
```{r}
figure <- ggarrange(carbon, nitrogen, ratio,
                    ncol = 3, nrow = 1)
figure

png("rex_biomass_cn_regression_2022.png", units="in", width=15, height=5, res=300)
ggpubr::ggarrange(carbon, nitrogen, ratio,
                                nrow = 1, ncol = 3, common.legend = T, legend="right",
                                align = "v")
dev.off()
```

C:N Ratio models
```{r}
#### Data exploration ###
# checking raw data
hist(trpr_cn$CN_ratio)
qqnorm(trpr_cn$CN_ratio)

# Exploring distributions for these data:
descdist(trpr_cn$CN_ratio, discrete = FALSE)

# checking model with log transformation (untransformed data was right skewed)
# is it normally distributed? no
m1 <- lm(CN_ratio ~ Subplot_Descriptions, data=trpr_cn)
outlierTest(m1)
hist(resid(m1))
qqnorm(resid(m1))
shapiro.test(resid(m1))
# homogeneity of variance? yes if p >0.05 (no significant difference between the group variances)
leveneTest(residuals(m1) ~ trpr_cn$Subplot_Descriptions)

m_plot1 <- lmer(CN_ratio ~ Subplot_Descriptions + Dried_Plant_Biomass_gram + (1|Rep/Footprint_Location), data=trpr_cn, REML=F)
hist(resid(m_plot1))
shapiro.test(resid(m_plot1))
summary(m_plot1)
anova(m_plot1)
emmeans(m_plot1, list(pairwise ~ Subplot_Descriptions), adjust = "tukey")
```

