---
title: "T7 warmx Trpr CN 2022 Plots"
author: "Moriah Young"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

COLLABORATORS: Adrian Noecker, Phoebe Zarnetske, Mark Hammond
DATA INPUT:  csv from the shared Google drive  
DATA OUTPUT: Code and Rmd are in the scripts folder in Github  
PROJECT: REX


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Clear all existing data
rm(list=ls())

# Load packages
library(tidyverse)
library(plotrix)
library(rstatix)
library(car)
library(ggpubr)

# Set working directory from .Renviron
dir <- Sys.getenv("DATA_DIR")
list.files(dir)

# Read in data
trpr_cn <- read.csv(file.path(dir, "T7_warmx_plant_traits/L1/T7_warmx_CN_Trpr_2022_L1.csv")) # 2022 CN Trpr data
alive <- subset(trpr_cn, Species_Code == "Trfpr (alive)")
dead <- subset(trpr_cn, Species_Code == "Trfpr (dead)")

#making order for graph
level_order_1 <- c('irrigated_control', 'ambient', 'drought', 'warmed','warmed_drought')

```

Calculating C:N ratios
```{r}
trpr_cn$CN_ratio <- trpr_cn$Carbon/trpr_cn$Nitrogen

# average not considering alive vs dead samples
ratio_rep_avg1 <- trpr_cn %>%
  group_by(Unique_ID, Subplot_Descriptions) %>%
  summarize(avg_rep_ratio = mean(CN_ratio, na.rm = TRUE),
            se = std.error(CN_ratio, na.rm = TRUE))

ratio_treatment_avg1 <- trpr_cn %>%
  group_by(Subplot_Descriptions) %>%
  summarize(avg_ratio = mean(CN_ratio, na.rm = TRUE),
            se = std.error(CN_ratio, na.rm = TRUE))
```

Carbon
```{r}
# Average by cn weighsheet replicate
carbon_rep_avg <- trpr_cn %>%
  group_by(Unique_ID, Species_Code, Subplot_Descriptions) %>%
  summarize(avg_rep_carbon = mean(Carbon, na.rm = TRUE),
            se = std.error(Carbon, na.rm = TRUE))

carbon_treatment_avg <- trpr_cn %>%
  group_by(Species_Code, Subplot_Descriptions) %>%
  summarize(avg_carbon = mean(Carbon, na.rm = TRUE),
            se = std.error(Carbon, na.rm = TRUE))

# average not considering alive vs dead samples
carbon_rep_avg1 <- trpr_cn %>%
  group_by(Unique_ID, Subplot_Descriptions) %>%
  summarize(avg_rep_carbon = mean(Carbon, na.rm = TRUE),
            se = std.error(Carbon, na.rm = TRUE))

carbon_treatment_avg1 <- trpr_cn %>%
  group_by(Subplot_Descriptions) %>%
  summarize(avg_carbon = mean(Carbon, na.rm = TRUE),
            se = std.error(Carbon, na.rm = TRUE))

# just alive
# carbon
alive_carbon_rep_avg <- alive %>%
  group_by(Unique_ID, Subplot_Descriptions) %>%
  summarize(avg_rep_carbon = mean(Carbon, na.rm = TRUE),
            se = std.error(Carbon, na.rm = TRUE))

alive_carbon_treatment_avg <- trpr_cn %>%
  group_by(Subplot_Descriptions) %>%
  summarize(avg_carbon = mean(Carbon, na.rm = TRUE),
            se = std.error(Carbon, na.rm = TRUE))

# nitrogen
alive_nitrogen_rep_avg <- alive %>%
  group_by(Unique_ID, Subplot_Descriptions) %>%
  summarize(avg_rep_nitrogen = mean(Nitrogen, na.rm = TRUE),
            se = std.error(Nitrogen, na.rm = TRUE))

alive_nitrogen_treatment_avg <- alive %>%
  group_by(Subplot_Descriptions) %>%
  summarize(avg_nitrogen = mean(Nitrogen, na.rm = TRUE),
            se = std.error(Nitrogen, na.rm = TRUE))
```

Nitrogen
```{r}
# Average by cn weighsheet replicate
nitrogen_rep_avg <- trpr_cn %>%
  group_by(Unique_ID, Species_Code, Subplot_Descriptions) %>%
  summarize(avg_rep_nitrogen = mean(Nitrogen, na.rm = TRUE),
            se = std.error(Nitrogen, na.rm = TRUE))

nitrogen_treatment_avg <- trpr_cn %>%
  group_by(Species_Code, Subplot_Descriptions) %>%
  summarize(avg_nitrogen = mean(Nitrogen, na.rm = TRUE),
            se = std.error(Nitrogen, na.rm = TRUE))

# average not considering alive vs dead samples
nitrogen_rep_avg1 <- trpr_cn %>%
  group_by(Unique_ID, Subplot_Descriptions) %>%
  summarize(avg_rep_nitrogen = mean(Nitrogen, na.rm = TRUE),
            se = std.error(Nitrogen, na.rm = TRUE))

nitrogen_treatment_avg1 <- trpr_cn %>%
  group_by(Subplot_Descriptions) %>%
  summarize(avg_nitrogen = mean(Nitrogen, na.rm = TRUE),
            se = std.error(Nitrogen, na.rm = TRUE))
```

Box Plots - alive vs. dead samples
```{r}
# Carbon
png("T7_warmx_Trpr_Carbon_2022.png", units="in", width=8, height=6, res=300)
ggplot(carbon_rep_avg, aes(x = factor(Subplot_Descriptions, levels = level_order_1), y = avg_rep_carbon, fill = Subplot_Descriptions)) +
        geom_jitter(shape=16, position=position_jitterdodge(), alpha = 0.6, aes(colour = Subplot_Descriptions)) +
        geom_boxplot(color = "black", outlier.shape = NA) +
        facet_wrap(~Species_Code, scales = "free_x") +
        scale_fill_manual(values = c("ambient" = "darkblue", "drought" = "gray58", 
        "irrigated_control" = "deepskyblue", "warmed" = "red2", "warmed_drought" = "darkred")) +
        labs(x = "Treatment", y = "2022 Red Clover Carbon (%)") +
        scale_x_discrete(labels=c("ambient" = "Ambient",
                                  "drought" = "Drought",
                                  "irrigated_control" = "Irrigated \n Control",
                                  "warmed" = "Warmed",
                                  "warmed_drought" = "Warmed +\n Drought")) +
        theme(legend.position = "none")
dev.off()

# Nitrogen
png("T7_warmx_Trpr_Nitrogen_2022.png", units="in", width=8, height=6, res=300)
ggplot(nitrogen_rep_avg, aes(x = factor(Subplot_Descriptions, levels = level_order_1), y = avg_rep_nitrogen, fill = Subplot_Descriptions)) +
        geom_jitter(shape=16, position=position_jitterdodge(), alpha = 0.6, aes(colour = Subplot_Descriptions)) +
        geom_boxplot(color = "black", outlier.shape = NA) +
        facet_wrap(~Species_Code, scales = "free_x") +
        scale_fill_manual(values = c("ambient" = "darkblue", "drought" = "gray58", 
        "irrigated_control" = "deepskyblue", "warmed" = "red2", "warmed_drought" = "darkred")) +
        labs(x = "Treatment", y = "2022 Red Clover Nitrogen (%)") +
        scale_x_discrete(labels=c("ambient" = "Ambient",
                                  "drought" = "Drought",
                                  "irrigated_control" = "Irrigated \n Control",
                                  "warmed" = "Warmed",
                                  "warmed_drought" = "Warmed +\n Drought")) +
        theme(legend.position = "none")
dev.off()
```

Just alive samples
```{r}
# Carbon
carbon_alive <- ggplot(alive_carbon_rep_avg, aes(x = factor(Subplot_Descriptions, levels = level_order_1), y = avg_rep_carbon, fill = Subplot_Descriptions)) +
        #geom_jitter(shape=16, position=position_jitterdodge(), alpha = 0.6, aes(colour = Subplot_Descriptions)) +
        geom_boxplot(color = "black", outlier.shape = NA) +
        scale_fill_manual(values = c("ambient" = "darkblue", "drought" = "gray58", 
        "irrigated_control" = "deepskyblue", "warmed" = "red2", "warmed_drought" = "darkred")) +
        labs(x = "Treatment", y = "Carbon (%)") +
        scale_x_discrete(labels=c("ambient" = "Ambient",
                                  "drought" = "Drought",
                                  "irrigated_control" = "Irrigated \n Control",
                                  "warmed" = "Warmed",
                                  "warmed_drought" = "Warmed +\n Drought")) +
        theme(legend.position = "none")

# Nitrogen
#png("T7_warmx_Trpr_Nitrogen_2022.png", units="in", width=8, height=6, res=300)
nitrogen_alive <- ggplot(alive_nitrogen_rep_avg, aes(x = factor(Subplot_Descriptions, levels = level_order_1), y = avg_rep_nitrogen, fill = Subplot_Descriptions)) +
        #geom_jitter(shape=16, position=position_jitterdodge(), alpha = 0.6, aes(colour = Subplot_Descriptions)) +
        geom_boxplot(color = "black", outlier.shape = NA) +
        scale_fill_manual(values = c("ambient" = "darkblue", "drought" = "gray58", 
        "irrigated_control" = "deepskyblue", "warmed" = "red2", "warmed_drought" = "darkred")) +
        labs(x = "Treatment", y = "Nitrogen (%)") +
        scale_x_discrete(labels=c("ambient" = "Ambient",
                                  "drought" = "Drought",
                                  "irrigated_control" = "Irrigated \n Control",
                                  "warmed" = "Warmed",
                                  "warmed_drought" = "Warmed +\n Drought")) +
        theme(legend.position = "none")
#dev.off()

figure <- ggarrange(carbon_alive, nitrogen_alive,
                    ncol = 2, nrow = 1)
figure
```

# Graphs that combined alive and dead C or N values together
```{r}
# Carbon
ggplot(carbon_rep_avg1, aes(x = factor(Subplot_Descriptions, levels = level_order_1), y = avg_rep_carbon, fill = Subplot_Descriptions)) +
        geom_jitter(shape=16, position=position_jitterdodge(), alpha = 0.6, aes(colour = Subplot_Descriptions)) +
        geom_boxplot(color = "black", outlier.shape = NA) +
        scale_fill_manual(values = c("ambient" = "darkblue", "drought" = "gray58", 
        "irrigated_control" = "deepskyblue", "warmed" = "red2", "warmed_drought" = "darkred")) +
        labs(x = "Treatment", y = "2022 Red Clover Carbon (%)") +
        scale_x_discrete(labels=c("ambient" = "Ambient",
                                  "drought" = "Drought",
                                  "irrigated_control" = "Irrigated \n Control",
                                  "warmed" = "Warmed",
                                  "warmed_drought" = "Warmed +\n Drought")) +
        theme(legend.position = "none")

# Nitrogen
#png("T7_warmx_Trpr_Nitrogen_2022.png", units="in", width=8, height=6, res=300)
ggplot(nitrogen_rep_avg1, aes(x = factor(Subplot_Descriptions, levels = level_order_1), y = avg_rep_nitrogen, fill = Subplot_Descriptions)) +
        geom_jitter(shape=16, position=position_jitterdodge(), alpha = 0.6, aes(colour = Subplot_Descriptions)) +
        geom_boxplot(color = "black", outlier.shape = NA) +
        scale_fill_manual(values = c("ambient" = "darkblue", "drought" = "gray58", 
        "irrigated_control" = "deepskyblue", "warmed" = "red2", "warmed_drought" = "darkred")) +
        labs(x = "Treatment", y = "2022 Red Clover Nitrogen (%)") +
        scale_x_discrete(labels=c("ambient" = "Ambient",
                                  "drought" = "Drought",
                                  "irrigated_control" = "Irrigated \n Control",
                                  "warmed" = "Warmed",
                                  "warmed_drought" = "Warmed +\n Drought")) +
        theme(legend.position = "none")

#dev.off()
```

CN ratio
```{r}
ggplot(trpr_cn, aes(x = factor(Subplot_Descriptions, levels = level_order_1), y = CN_ratio, fill = Subplot_Descriptions)) +
        geom_jitter(shape=16, position=position_jitterdodge(), alpha = 0.6, aes(colour = Subplot_Descriptions)) +
        geom_boxplot(color = "black", outlier.shape = NA) +
        scale_fill_manual(values = c("ambient" = "darkblue", "drought" = "gray58", 
        "irrigated_control" = "deepskyblue", "warmed" = "red2", "warmed_drought" = "darkred")) +
        labs(x = "Treatment", y = "C:N Ratio") +
        scale_x_discrete(labels=c("ambient" = "Ambient",
                                  "drought" = "Drought",
                                  "irrigated_control" = "Irrigated \n Control",
                                  "warmed" = "Warmed",
                                  "warmed_drought" = "Warmed +\n Drought")) +
        theme(legend.position = "none")
```

